language: java
jdk: oraclejdk8
sudo: false
script: 
  - mvn clean verify
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2
deploy:
  -
    on:
      branch: release
    provider: bintray
    skip_cleanup: true
    file: target/bin/bintray.json
    user: ocularminds
    key: $BINTRAY_API_KEY